#https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: power-model
channels:
  - anaconda
  - conda-forge
  - defaults 
  - pip
dependencies:
 - pandas 
 - numpy 
 - glpk
 - pyyaml
 - plotly
 - pip
 - pip:
   - otoole
   - mip
   - graphvis
